play_motion:
  motions:
    s12:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to step1
        - time_from_start: 3
          positions: [1.2031763542929022, 0.24058691343631596, -1.141419832640476, 0.6876227676448481, -1.6893868773482137, 0.5091112543814796, -1.5757505020638343]
        #go to step2
        - time_from_start: 5
          positions: [1.2031763542929022, 0.19058691343631596, -1.141419832640476, 0.6876227676448481, -1.6893868773482137, 0.5091112543814796, -1.5757505020638343]
        #go to step3
        - time_from_start: 7
          positions: [1.2031763542929022, 0.24058691343631596, -1.141419832640476, 0.6876227676448481, -1.6893868773482137, 0.5091112543814796, -1.5757505020638343]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s12
        usage: s12
        description: suggest the solution for p12
