play_motion:
  motions:
    s21:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to p23
        - time_from_start: 3
          positions: [1.1594266419181152, 0.3438865498780469, -1.1346242076117137, 0.9898363312828852, -1.6819281725617483, 0.5630266112358551, -1.5764433872079322]
        #go to p21
        - time_from_start: 5
          positions: [1.1594266419181152, 0.2938865498780469, -1.1346242076117137, 0.9898363312828852, -1.6819281725617483, 0.5630266112358551, -1.5764433872079322]
        #go to p22
        - time_from_start: 7
          positions: [1.1594266419181152, 0.3438865498780469, -1.1346242076117137, 0.9898363312828852, -1.6819281725617483, 0.5630266112358551, -1.5764433872079322]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s21
        usage: s21
        description: suggest the solution fpr p21
