play_motion:
  motions:
    c21:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.0698, 0.1197, -1.2999, 1.01, -1.6298, 0.5703, -1.5803]
        - time_from_start: 2
          positions: [1.0608, 0.182, -1.3074, 1.034, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: c21
        usage: c21
        description: coming back a token in position c21 with intermediate point