play_motion:
  motions:
    c31:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9902, 0.2905, -1.2072, 1.3062, -1.6315, 0.5706, -1.5775]
        - time_from_start: 2
          positions: [0.9706, 0.3627, -1.269, 1.3155, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: c31
        usage: c31
        description: place a token in position c31 with intermediate point