play_motion:
  motions:
    o11:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.3082094120173648, 0.1174848563407937, -1.141419832640476, 0.6464194971544279, -1.6435415945250957, 0.5091094017474045, -1.5757523546979095]
        - time_from_start: 5
          positions: [1.3082094120173648, 0.2074848563407937, -1.141419832640476, 0.6464194971544279, -1.6435415945250957, 0.5091094017474045, -1.5757523546979095]
        - time_from_start: 10
          positions: [1.4505, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o11
        usage: o11
        description: offer token o11  to user right side
