play_motion:
  motions:
    o12:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.2031763542929022, 0.14058691343631596, -1.141419832640476, 0.6876227676448481, -1.6893868773482137, 0.5091112543814796, -1.5757505020638343]
        - time_from_start: 5
          positions: [1.2031763542929022, 0.24058691343631596, -1.141419832640476, 0.6876227676448481, -1.6893868773482137, 0.5091112543814796, -1.5757505020638343]
        - time_from_start: 10
          positions: [1.4505, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o12
        usage: o12
        description: offer token in position p12 to user
