play_motion:
  motions:
    o13:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.087113828406633, 0.1648241313718572, -1.1414044926291245, 0.7375545045943334, -1.7338093372016332, 0.526396330302424, -1.5740646050554679]
        - time_from_start: 5
          positions: [1.087113828406633, 0.2648241313718572, -1.1414044926291245, 0.7375545045943334, -1.7338093372016332, 0.526396330302424, -1.5740646050554679]
        - time_from_start: 10
          positions: [1.4505, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o13
        usage: o13
        description: offer token in position p13 to user
