play_motion:
  motions:
    o14:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9962856211937597, 0.1644713111107702, -1.1414044926291245, 0.7384135452300234, -1.7575601060447745, 0.4956703941664258, -1.5727696138369534]
        - time_from_start: 2
          positions: [0.9962856211937597, 0.2644713111107702, -1.1414044926291245, 0.7384135452300234, -1.7575601060447745, 0.4956703941664258, -1.5727696138369534]
        - time_from_start: 10
          positions: [0.6997, 0.2705, -1.1202, 0.6501, -1.5499, 0.5702, -1.5802]
      meta:
        name: o14
        usage: o14
        description: offer token in position p14 to user
