play_motion:
  motions:
    o23:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9264885695439415, 0.2852125404592799, -1.1305591046035375, 1.0619497246467962, -1.7067682902410648, 0.5630266112358551, -1.5764433872079322]
        - time_from_start: 2
          positions: [0.9264885695439415, 0.3852125404592799, -1.1305591046035375, 1.0619497246467962, -1.7067682902410648, 0.5630266112358551, -1.5764433872079322]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o23
        usage: o23
        description: offer token in location p23  to user 
