play_motion:
  motions:
    o31:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [1.0974683360689688, 0.46300327202442126, -1.0730800820690607, 1.31110218901962, -1.7182546215068584, 0.5630266112358551, -1.5764433872079322]
        - time_from_start: 5
          positions: [1.0974683360689688, 0.56300327202442126, -1.0730800820690607, 1.31110218901962, -1.7182546215068584, 0.5630266112358551, -1.5764433872079322]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o31
        usage: o31
        description: offer token in position p31 to user
