play_motion:
  motions:
    o32:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.9701002218165642, 0.49922103882556873, -1.0709785005138903, 1.364332028409701, -1.7307858383910244, 0.5630266112358551, -1.5764433872079322]
        - time_from_start: 5
          positions: [0.9701002218165642, 0.59922103882556873, -1.0709785005138903, 1.364332028409701, -1.7307858383910244, 0.5630266112358551, -1.5764433872079322]
        - time_from_start: 10
          positions: [1.4105, 0.2109, -1.1399, 0.6501, -1.5298, 0.57, -1.58]
      meta:
        name: o32
        usage: o32
        description: offer token p32  to user right side
