play_motion:
  motions:
    p34:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.6386, 0.543, -1.1834, 1.3668, -1.6315, 0.5706, -1.5775]
        - time_from_start: 5
          positions: [0.6274, 0.3311, -1.1834, 1.3083, -1.6315, 0.5706, -1.5775]
        - time_from_start: 7
          positions: [0.6274, 0.3213, -1.1835, 1.3082, -1.6314, 0.5706, -1.5776]
      meta:
        name: p34
        usage: p34
        description: pick a token in position p34 with intermediate point