play_motion:
  motions:
    p43:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        - time_from_start: 3
          positions: [0.5276, 0.453, -1.3407, 1.6121, -1.6313, 0.5705, -1.5776]
        - time_from_start: 5
          positions: [0.5, 0.3006, -1.34, 1.6001, -1.63, 0.57, -1.58]
        - time_from_start: 10
          positions: [0.5255, 0.2298, -1.2883, 1.5815, -1.63, 0.57, -1.58]
      meta:
        name: p43
        usage: p43
        description: pick a token in position p43 with intermediate point