play_motion:
  motions:
    s11:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to step1
        - time_from_start: 3
          positions: [1.3082094120173648, 0.2474848563407937, -1.141419832640476, 0.6464194971544279, -1.6435415945250957, 0.5091094017474045, -1.5757523546979095]
        #go to step2
        - time_from_start: 5
          positions: [1.3082094120173648, 0.1974848563407937, -1.141419832640476, 0.6464194971544279, -1.6435415945250957, 0.5091094017474045, -1.5757523546979095]
        #go to step3
        - time_from_start: 7
          positions: [1.3082094120173648, 0.2474848563407937, -1.141419832640476, 0.6464194971544279, -1.6435415945250957, 0.5091094017474045, -1.5757523546979095]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]


      meta:
        name: s11
        usage: s11
        description: suggest the solution for p11
