play_motion:
  motions:
    s13:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to step1
        - time_from_start: 3
          positions: [1.087113828406633, 0.2448241313718572, -1.1414044926291245, 0.7375545045943334, -1.7338093372016332, 0.526396330302424, -1.5740646050554679]
        #go to step2
        - time_from_start: 5
          positions: [1.087113828406633, 0.1948241313718572, -1.1414044926291245, 0.7375545045943334, -1.7338093372016332, 0.526396330302424, -1.5740646050554679]
        #go to step3
        - time_from_start: 7
          positions: [1.087113828406633, 0.2448241313718572, -1.1414044926291245, 0.7375545045943334, -1.7338093372016332, 0.526396330302424, -1.5740646050554679]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s13
        usage: s13
        description: suggest the solution for p13
