play_motion:
  motions:
    s14:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to p14
        - time_from_start: 3
          positions: [0.9962856211937597, 0.2444713111107702, -1.1414044926291245, 0.7384135452300234, -1.7575601060447745, 0.4956703941664258, -1.5727696138369534]
        #go to p13
        - time_from_start: 5
          positions: [0.9962856211937597, 0.1944713111107702, -1.1414044926291245, 0.7384135452300234, -1.7575601060447745, 0.4956703941664258, -1.5727696138369534]
        #go to p12
        - time_from_start: 7
          positions: [0.9962856211937597, 0.2444713111107702, -1.1414044926291245, 0.7384135452300234, -1.7575601060447745, 0.4956703941664258, -1.5727696138369534]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s14
        usage: s14
        description: suggest the solution for p14
