play_motion:
  motions:
    s15:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to 1ststep
        - time_from_start: 3
          positions: [0.9361527766954548, 0.24798248630903985, -1.1344401274754943, 0.7013213977818343, -1.7946053770110342, 0.46875717895704105,-1.5704964318267713]
        #go to 2ndstep
        - time_from_start: 5
          positions: [0.9361527766954548, 0.19798248630903985, -1.1344401274754943, 0.7013213977818343, -1.7946053770110342, 0.46875717895704105,-1.5704964318267713]
        #go to 3rdstep
        - time_from_start: 7
          positions: [0.9361527766954548, 0.24798248630903985, -1.1344401274754943, 0.7013213977818343, -1.7946053770110342, 0.46875717895704105,-1.5704964318267713]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s15
        usage: s15
        description: suggest the solution for p15
