play_motion:
  motions:
    s23:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to first step
        - time_from_start: 3
          positions: [0.9264885695439415, 0.3852125404592799, -1.1305591046035375, 1.0619497246467962, -1.7067682902410648, 0.5630266112358551, -1.5764433872079322]
        #go to second step
        - time_from_start: 5
          positions: [0.9264885695439415, 0.3352125404592799, -1.1305591046035375, 1.0619497246467962, -1.7067682902410648, 0.5630266112358551, -1.5764433872079322]
        #go to third step
        - time_from_start: 7
          positions: [0.9264885695439415, 0.3852125404592799, -1.1305591046035375, 1.0619497246467962, -1.7067682902410648, 0.5630266112358551, -1.5764433872079322]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s23
        usage: s23
        description: suggest the solution for p23
