play_motion:
  motions:
    s24:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to first step
        - time_from_start: 3
          positions: [0.8198601506389116, 0.40124116492046204, -1.1264173015386032, 1.060737863750019, -1.71625007143757, 0.5630266112358551, -1.5764433872079322]
        #go to second step
        - time_from_start: 5
          positions: [0.8198601506389116, 0.33124116492046204, -1.1264173015386032, 1.060737863750019, -1.71625007143757, 0.5630266112358551, -1.5764433872079322]
        #go to third step
        - time_from_start: 7
          positions: [0.8198601506389116, 0.40124116492046204, -1.1264173015386032, 1.060737863750019, -1.71625007143757, 0.5630266112358551, -1.5764433872079322]
        #come back
        - time_from_start: 10
          positions: [0.2269, 0.3316, -1.6138, 2.2556, -1.6316, 0.5703, -1.5773]
      meta:
        name: s24
        usage: s24
        description: suggest the solution for p24
