play_motion:
  motions:
    ss12:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to p13
        - time_from_start: 3
          positions: [1.0323, 0.226, -1.1412, 0.7324, -1.55, 0.5702, -1.5802]
        #go to p11
        - time_from_start: 5
          positions: [1.2786, 0.1891, -1.1414, 0.6463, -1.5298, 0.5698, -1.5781]
        #go to p13
        - time_from_start: 7
          positions: [1.0323, 0.226, -1.1412, 0.7324, -1.55, 0.5702, -1.5802]
        #come back
        - time_from_start: 10
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: ss12
        usage: ss12
        description: suggest a subset of solution from p12