play_motion:
  motions:
    ss24:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
        - time_from_start: 0
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
        #go to p25
        - time_from_start: 3
          positions: [0.64, 0.22, -1.2499, 1.0199, -1.6, 0.5399, -1.5499]
        #go to p23
        - time_from_start: 5
          positions: [0.8251, 0.223, -1.3074, 1.0541, -1.6315, 0.5706, -1.5775]
        #go to p25
        - time_from_start: 7
          positions: [0.64, 0.22, -1.2499, 1.0199, -1.6, 0.5399, -1.5499]
        #come back
        - time_from_start: 10
          positions: [0.68, 0.2706, -1.3499, 1.3701, -1.6295, 0.5699, -1.5799]
      meta:
        name: ss24
        usage: ss24
        description: suggest a subset of solution from p24